// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import {env} from "./src/config/env";
import { defineConfig } from "prisma/config";

const databaseUrl = env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("Missing DATABASE_URL in environment variables");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
